app/views/events/partials/_events_map.html.erb, app/views/events/show.html.erb
Max zoom level of 15 for the maps on the events pages.
Closes #617
=> Max zoom level

config/routes.rb
When precompiling the assets no database connection is available, so we can't have devise search for one. There was a check, but that was more or less checking if it was run through rake. Running `rake db:setup` would also trigger it, and cause problems as devise would not be correctly initialized. This fixes that.
=> Make devise exclude more specific

app/models/event.rb, app/models/material.rb, app/models/user.rb, app/models/workflow.rb, lib/tasks/check_urls.rake, test/models/star_test.rb, test/models/user_test.rb
Three small bugs fixed:
External resources in the check_urls task weren't checked.
Starring a material -> deleting that material -> checking starred materials led to an error page.
The relation was not set up properly, stars of a material weren't getting deleted after the material was.
Same thing for events and workflows.
It was possible to register an account without checking the privacy policy checkbox.
=> Small bug fixes

app/models/event.rb, app/views/content_providers/_content_provider.html.erb, app/views/content_providers/show.html.erb, app/views/nodes/show.html.erb, lib/tasks/tess.rake
On the event index page all events which have not yet finished are shown. On the content provider page, all events which have not yet started are shown.
This difference has been confusing some of our content providers, so I propose to change it to be
upcoming events are those which have not yet ended.
=> harmonize upcoming? definition with event filter page

app/models/event.rb, test/controllers/content_providers_controller_test.rb
This causes the event totals on the content provider page to match up with the shown and hidden count.
If you wish not to have this, perhaps we could explicitly include them in the view then, instead of in this scope, or update the text on the view to explain why events without date are also hidden.
example:
=> include events without date in not_finished

app/views/subscriptions/_subscribe_button.html.erb, app/views/subscriptions/_subscribe_to_rss_modal.html.erb
Directly downloading the RSS file is not so useful typically (but can still be done by clicking the link in the text)
=> Add modal for RSS URL

Gemfile, Gemfile.lock
Debase is incompatible with Ruby 3 on an M1 mac, with errors like symbol not found in flat namespace '_RHASH_EMPTY_P'
and it is also not so actively maintained, so we are probably better of moving to pry.
- Remove debase and ruby-debug-ide from Gemfile, replace with pry-byebug
Needed for compatibility with my M1 Mac.
**Checklist**
=> Replace debase with pry-byebug

app/mailers/subscription_mailer.rb, app/models/user.rb, app/views/subscription_mailer/digest.html.erb, app/views/subscription_mailer/digest.text.erb, test/mailers/subscription_mailer_test.rb
- Add a list of links to owned & collaborated collections to the digest emails (text & html)
Fixes #790 
Builds on the collections-ui branch, so merge that one before reviewing this.
Make it a trigger point for keeping your curated collection up to date
**Checklist**
=> Collection link in digest mail

app/models/user.rb, config/initializers/devise.rb, test/integration/devise_mailer_test.rb
- Changes Devise's config to inherit its' mailer class from `ApplicationMailer`.
- This ensures custom headers etc. are set.
Confirmation emails etc. were not having these headers applied and so were bouncing.
**Checklist**
=> Ensure devise's mailer sets configured headers

db/migrate/20180426141503_fix_nil_sponsors.rb, db/migrate/20230103132957_upgrade_paperclip_attachment_size_to_big_int.rb, db/schema.rb
In another PR I ran into an issue where some old tables were left in schema.rb. The typical way to do that is to reload the schema and then redo the migration, but it should also be possible to regenerate the schema by executing all migrations.
I was trying this latter approach, and ran into this issue:
```
== 20180426141503 FixNilSponsors: migrating ===================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
can't cast Array
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:246:in `_type_cast'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/quoting.rb:162:in `_type_cast' …
```
=> redo migrations to recreate schema.rb

app/controllers/application_controller.rb, app/views/static/error.html.erb, config/application.rb, config/locales/en.yml, config/routes.rb, test/controllers/curator_controller_test.rb, test/integration/error_handler_test.rb, test/integration/identifier_resolution_test.rb
- Renders appropriate pages when an error occurs.
- Uses I18n for error messages so they can be customised.
#797 
**Checklist**
=> Fix error pages not being renderer. Fixes #797

app/views/static/home/_provider_carousel.html.erb, config/tess.example.yml
Changed the number of providers appearing in the carroussel to a config variable
We want to change this number in the Taxila fork. This is a non-intrusive way of doing so while also getting rid of a hard coded variable in the main Tess branch.
**Checklist**
=> Configurable number of providers in carousel on home page

app/views/nodes/_node.html.erb, app/views/nodes/show.html.erb
- Refreshes the node index and show pages.
- Hides unverified users' content
Nodes with lots of providers had the events/materials hidden under a long list. Also noticed some spam content on a node page.
**Checklist**
=> Node improvements

app/views/static/home/_provider_carousel.html.erb, test/controllers/static_controller_test.rb
- Adds the `from_verified_users` filter to the provider selection that is used in the carousel on the front page (when no explicit provider IDs are specified).
A spam provider was showing up, and this is likely to happen again as it shows the most recent providers.
**Checklist**
=> Hide unverified users' providers from carousel

app/dictionaries/online_keywords_dictionary.rb, app/models/event.rb, config/dictionaries/online_keywords.yml, config/tess.example.yml, test/models/event_test.rb, test/unit/ingestors/eventbrite_ingestor_test.rb
Before event save, check whether any keywords are found in other dictionaries and put the values in the corresponding var.
Before event save, find whether event is online by scanning venue and description for entries from dictionaries
Lots of scraped online events end up as face-to-face events because the provider does not have a good way to get the information directly.
**Checklist**
=> Relocate keywords that belong to other variables when scraping

app/models/concerns/has_external_resources.rb
- Make sure external resource titles are indexed for the text search, not just for faceting.
@egonw discovered his materials were not findable via search after annotating with bio.tool tools.
Also, bio.tools is currently linking back to TeSS using the tool name in the text search query parameter (https://github.com/bio-tools/biotoolsRegistry/issues/80#issuecomment-1496227469), which would currently not find any tools unless they were mentioned in other metadata fields.
**Checklist**
=> Index `external resource` titles for text search

app/models/profile.rb, app/models/user.rb, config/initializers/devise.rb, test/controllers/curator_controller_test.rb, test/fixtures/users.yml, test/integration/login_test.rb, test/models/user_test.rb, test/test_helper.rb
- Prevent registration with the same username/email address using different cases
- Re-assign workflows and collections to the default user if a user is deleted (as with other resource types)
- Add a method to merge user accounts
Discovered a user in production with multiple accounts using the same email address, but with different cases.
#829 
**Checklist**
=> Case insensitive username/email validation

lib/scraper.rb, test/config/test_ingestion_disabled.yml, test/fixtures/sources.yml, test/unit/ingestors/scraper_test.rb
- Builds upon previous PR to also skip unapproved sources when scraping.
- Also fixes logging issue when scraping sources from database.
It was discovered that disabled/unapproved sources were still being scraped.
**Checklist**
=> Make sure unapproved sources are skipped

app/models/autocomplete_suggestion.rb, app/models/collection.rb, app/models/content_provider.rb, app/models/event.rb, app/models/material.rb, app/models/profile.rb, app/models/user.rb, app/models/workflow.rb, lib/array_field_cleaner.rb, test/controllers/users_controller_test.rb, test/models/collection_test.rb, test/models/content_provider_test.rb, test/models/event_test.rb, test/models/material_test.rb, test/models/profile_test.rb, test/models/user_test.rb, test/models/workflow_test.rb, test/unit/autocomplete_suggestion_test.rb, test/unit/ingestors/wur_ingestor_test.rb
- Updates `array_field_cleaner` to also strip strings.
- Adds `auto_strip_attributes` to various models that didn't have it before.
- Strip autocomplete suggestions.
Noticed a seemingly duplicate keyword suggestion on the dev server (`AAI` and `AAI `).
**Checklist**
=> Strip leading/trailing whitespace from attributes

app/views/static/home/_provider_carousel.html.erb
- Changes carousel cache key to be based on latest `updated_at` of displayed providers.
A provider updated their logo and TeSS was displaying a broken image in the carousel.
**Checklist**
=> Expire carousel if content provider changes image

app/helpers/nodes_helper.rb, app/models/node.rb, config/data/countries.json, test/controllers/nodes_controller_test.rb, test/fixtures/files/node_test_data.json, test/models/node_test.rb
- Validates a Node's country code against the dictionary of countries.
Node index was crashing when a node was created without filling out that field.
**Checklist**
=> Validate node country

app/models/user.rb, test/controllers/users_controller_test.rb
- Ensures newly registered users are listed when autocompleting (e.g. when adding editors to a content provider)
#867
**Checklist**
=> Include new users in autocompletes. Fixes #867

app/helpers/application_helper.rb, app/models/material.rb, app/views/materials/show.html.erb, app/views/search/common/_facet_sidebar.html.erb, config/locales/en.yml, lib/facets.rb, test/controllers/materials_controller_test.rb, test/models/material_test.rb
- Add filter for material "status".
- Hide materials flagged as "Archived" from the default results.
- Add a toggle to show archived materials (as is done for past events).
- Display a warning notice when viewing an archived material.
#870
Part of general curation activity to reduce amount of irrelevant content.
**Checklist**
=> Hide archived materials

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/dictionaries/licence_dictionary.rb, app/helpers/materials_helper.rb, app/views/materials/_form.html.erb, app/views/workflows/_form.html.erb, config/tess.example.yml, test/unit/licence_dictionary_test.rb, vendor/assets/stylesheets/select2-bootstrap-theme.scss
- Allow licence dropdown list to be filtered by typing (using `select2`).
- Group licences into 2 sections with more common ones near the top.
- Allow common licences to be configured.
#732
**Checklist**
=> Improved licence selection

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/helpers/application_helper.rb
- Automatically switch to anchored tags on load
- Push tab switches onto history
I'd like to be able to deeplink to the calendar / map views
Note that we'd need to update that tab since it only loads the calendar once we click (and I expect the map to behave the same?)
**Checklist**
=> use bootstrap-tab-history to pop tab switches onto history

app/models/event.rb, app/views/events/index.html.erb, config/application.rb, test/config/test_secrets.yml, test/controllers/events_controller_test.rb, test/fixtures/edit_suggestions.yml, test/integration/cookie_consent_integration_test.rb, test/models/event_test.rb
- Hide map on index page if no API key.
- Tweak custom Config getters to be dynamic.
#879
Setting derived `TeSS::Config` properties on boot (e.g. `map_enabled`) made it hard to switch when testing.
**Checklist**
=> Hide map on index page if no API key. Fixes #879

app/views/content_providers/show.html.erb, app/views/search/index.html.erb
- Re-use tab helpers for search result tabs.
- Fix wrong setting hiding the sources tab on content provider page.
- Search tabs were not making use of tab history.
- Sources tab should be visible to admins even if users can't create them.
**Checklist**
=> Search tabs

Gemfile, Gemfile.lock, config/schedule.rb, config/sitemap.rb
- Replaces unmaintained sitemap gem
- Add collections to sitemap
- Provides real `lastmod` dates in sitemaps
Last update to previous gem was 10 years ago, and was not deployed to rubygems.
**Checklist**
=> Sitemap updates

app/views/content_providers/partials/_content_provider_sidebar.html.erb, config/tess.example.yml
Be able to disable 'Owner' and 'Type' in content provider sidebar for Taxila
**Checklist**
=> configurable content provider sidebar

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/sources_controller.rb, app/views/sources/_test_results.html.erb, app/views/sources/show.html.erb, lib/ingestors/bioschemas_ingestor.rb, lib/ingestors/ingestor.rb, lib/scraper.rb, test/unit/ingestors/bioschemas_ingestor_test.rb
- Report number of URLs crawled from sitemap in Bioschemas scraper.
- Report number of Bioschemas resources found.
- Improve the appearance of the output log (use of headings, grouping errors under each resource in a `ul`, etc.)
- Remove some redundant info (records read/written)
- Harmonize "Last Run" and "Test Result" views
Was not always apparent why a source "didn't work".
#822
**Checklist**
=> Report extra info when scraping/testing source

lib/ingestors/uva_ingestor.rb
default value of false for online in uva ingestor
if page did not have the proper field to be scraped then there would be no value for online and the events would have a json instead of an icon for their online status
**Checklist**
=> default of false for online in uva ingestor

app/models/event.rb, app/models/user.rb, app/views/materials/show.json.jbuilder, test/models/event_test.rb, test/models/user_test.rb
- Fix `presence` being nil/blank and loading wrong icon.
- Other small bug fixes. 
#904 
**Checklist**
=> Sync TeSS 1.4.1 changes

app/controllers/bioschemas_controller.rb, test/controllers/bioschemas_controller_test.rb, test/fixtures/files/ingestion/ols_relative_id.json
- Adds a dummy URL to the ingestor when testing Bioschemas content, allowing resources with relative `@id`s to be picked up.
JSON snippets e.g. 
```json
{
"@context": "https://schema.org",
"@type": "LearningResource",
"@id": "#some-resource"
}
```
were being ignored.
**Checklist**
=> Fix resources in JSON-LD snippets with relative `@id`s not being detected

app/views/curation_mailer/source_requires_approval.html.erb, app/views/curation_mailer/source_requires_approval.text.erb, app/views/curation_mailer/user_requires_approval.html.erb, app/views/curation_mailer/user_requires_approval.text.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/shared/_links.html.erb, app/views/static/showcase.html.erb
=> replace TeSS with config var

app/models/concerns/has_edam_terms.rb, app/models/event.rb, app/models/material.rb, app/models/workflow.rb, test/models/event_test.rb
- Index content by EDAM topic/operation synonyms as well as their exact names.
- Allow content to be queried by EDAM topic/operation (instead of just filtering).
https://docs.google.com/document/d/1Qt6ABVqkDRTulg6ZhLsKu8YYlGbvD-xQvQGoVHuUwow/edit
@bianchini88
**Checklist**
=> Synonyms for EDAM terms

config/initializers/content_security_policy.rb, config/initializers/permissions_policy.rb, test/integration/header_test.rb
- Adds Content-Security-Policy and Feature-Policy headers to responses.
#865
**Checklist**
=> Enable Content-Security-Policy and Feature-Policy headers

config/initializers/content_security_policy.rb, config/tess.example.yml
- add a csp_report_uri
can be used with sentry
**Checklist**
=> add option to use a specific csp reporting endpoint

app/assets/javascripts/sources.js, app/models/concerns/has_test_job.rb, app/workers/source_test_worker.rb, test/fixtures/files/ingestion/mentions.jsonld, test/workers/source_test_worker_test.rb
- Ensure only "safe" types are written to the source test result YAML.
Bioschemas sources with `mentions` (parsed as external resources) were breaking the source testing page.
**Checklist**
=> Fix deeply nested `ActionController::Parameters` breaking source test

app/controllers/application_controller.rb, app/controllers/bioschemas_controller.rb, test/controllers/application_controller_test.rb, test/controllers/bioschemas_controller_test.rb
- Add the `format: :plain` option to HTTParty calls to disregard incoming content-type to ensure response isn't parsed.
An endpoint with a JSON `Content-Type` header, but containing HTML caused a 500 error.
**Checklist**
=> Don't attempt to parse content when testing URLs

app/controllers/bioschemas_controller.rb, app/views/bioschemas/_test_results.html.erb, app/views/sources/_test_results.html.erb, lib/ingestors/bioschemas_ingestor.rb, test/controllers/bioschemas_controller_test.rb, test/unit/ingestors/bioschemas_ingestor_test.rb
- Catches and logs exceptions that occur when scraping Bioschemas sources.
- Fixes awkward formatting of error messages when markdown is rendered.
A user was trying to test a Bioschemas source, and a single page with a JSON error caused the entire ingestion to fail with a generic error message.
**Checklist**
=> Handle and log errors when ingesting bioschemas content

app/views/trainers/index.html.erb
Button on trainer page that lets people register themselves
Many people have trouble finding where to register as trainer
**Checklist**
=> add register as trainer button that directs to user edit

app/controllers/static_controller.rb, app/views/static/home.html.erb, app/views/static/home/_upcoming_events.html.erb, config/tess.example.yml, test/controllers/static_controller_test.rb
Add option to show number of upcoming events on home page.
**Checklist**
=> upcoming events on home page

app/models/user.rb, db/seeds.rb, test/models/user_test.rb
- Skips sending of confirmation emails when creating default user and admin user (in seeds).
Can cause a crash during seeding process in production if `sendmail` not installed and email not configured.
**Checklist**
=> Don't attempt to send confirmation emails for default & admin users

config/schedule.example.yml, config/schedule.rb, lib/tasks/check_urls.rake
- Adds a single rake task for checking event & material URLs
- Adds this task to the list of scheduled tasks
- Change logging to only report failing links
Currently in production we are running this task via an external script, but it makes sense to be part of the regular set of scheduled TeSS tasks.
**Checklist**
=> Add dead URL checking task to the schedule

app/helpers/events_helper.rb, test/controllers/events_controller_test.rb
- Removes organizer from RSS item title
- Adds organizer and event date to RSS item description
- #941 
- #942
**Checklist**
=> Event RSS tweaks

app/views/public_activity/learning_path/_add_topic.html.erb, test/controllers/learning_paths_controller_test.rb
- As in title
Ajax to load activity log on learning path page would throw 500. Error caught via sentry from dev server
**Checklist**
=> Fix misnamed learning path activity template

app/models/user.rb, test/models/user_test.rb
- Adds `User#purge` to delete user + resources.
Default deletion moves resources to the default user, which can be undesirable a times, for example when deleting spammers.
**Checklist**
=> Add method to delete user & resources (without re-assigning them)

lib/ingestors/ical_ingestor.rb, test/workers/source_test_worker_test.rb
- Converts Ical date objects to regular Time objects that are in the default list of classes allowed to be serialized to YAML
- #986
**Checklist**
=> Ensure ical ingestor results can be deserialized

app/assets/images/modern/icons/learning-paths-icon.svg, app/views/learning_paths/index.html.erb, app/views/static/home/_catalogue_blocks.html.erb, config/locales/en.yml
- Replaces the workflow block on the front page with one for learning paths (if enabled).
We are promoting LPs over workflows
**Checklist**
=> Replace workflows catalogue block with learning paths

app/controllers/content_providers_controller.rb, app/controllers/events_controller.rb, app/controllers/materials_controller.rb, app/controllers/workflows_controller.rb, app/helpers/application_helper.rb, app/policies/collection_policy.rb, app/policies/resource_policy.rb, app/policies/workflow_policy.rb, app/views/collections/show.html.erb, app/views/content_providers/show.html.erb, app/views/events/show.html.erb, app/views/materials/show.html.erb, app/views/users/_form.html.erb, app/views/workflows/show.html.erb, config/locales/en.yml, test/controllers/collections_controller_test.rb, test/controllers/content_providers_controller_test.rb, test/controllers/events_controller_test.rb, test/controllers/materials_controller_test.rb, test/controllers/workflows_controller_test.rb
- If a user is a basic user, or unverified user, don't show their content ever (previously it was hidden from indexes, but accessible directly).
- Displays a notice to the user explaining only they can see it.
- Admins/curators can still see this content.
Spam users
**Checklist**
=> Hide unverified user's content from other users

config/initializers/session_store.rb, db/migrate/20240702175333_drop_sessions.rb, db/schema.rb
- Store session data in encrypted cookies instead of a database table.
The `sessions` table in production accounts for 90%+ of the database size even when pruned of stale sessions. This table is written to every time an anonymous user visits TeSS. It's not clear why we moved away from the default cookie store implementation in the first place as we are not storing much data in the session.
**Checklist**
=> Switch back to cookie_store for sessions

app/models/concerns/has_language.rb, app/views/events/_form.html.erb, app/views/events/show.html.erb, test/controllers/events_controller_test.rb, test/models/event_test.rb
- Change Event language validation to accept empty string
- Allow language to be unset when editing an event
When creating an event through the UI, if you don't select a language from the drop down, the parameter is passed as `""`, which causes validation to fail.
**Checklist**
=> Handle `language` being blank (not just nil)

docker-compose-prod.yml
- mount the logs dir to /code/logs
Ingestor debugging is hard without seeing the logs.
**Checklist**
=> expose the logs dir outside of the production container

config/initializers/session_store.rb
- Switch SameSite attribute from "strict" to "lax"
LS-Login was broken, because with a `SameSite=strict` cookie, cookies are not sent immediately following a redirect, so Rails creates a new session for the user which does not have the stored OAuth2 state or nonce, causing verification to fail.
**Checklist**
=> Change cookie SameSite setting to "Lax"

app/policies/learning_path_policy.rb, config/data/roles.yml, test/controllers/learning_paths_controller_test.rb, test/fixtures/roles.yml, test/fixtures/users.yml
- Adds an extra user role - "Learning path curator"
Needed a role that allows modification of learning paths, but without the ability to edit all types resources (like the "curator" role provides).
**Checklist**
=> Learning Path curator role

app/views/about/_about_nav.html.erb, app/views/about/_links.html.erb, app/views/about/learning_paths.html.erb, test/controllers/about_controller_test.rb
- Hides the learning path block from the sidebar and footer of the "About" pages if the feature is switched off. Can still visit the page directly via URL though.
User confusion
**Checklist**
=> Hide learning paths help section if the feature is not enabled

app/views/search/common/_facet_sidebar.html.erb, app/views/search/common/_sort_by.html.erb, config/locales/en.yml
The strings used in the sort options for search now go through i18n.
As has come up elsewhere, a Canadian fork for TeSS is striving to make an English/French bilingual instance. There are many places in the TeSS code base where strings in the view don't go through i18n. This PR just handles just the sort options for searching. (Note: I think it might be better to send these improvements in smaller atomic PRs rather than in one mega-PR.)
**Checklist**
=> Make the sort options go through i18n.

app/views/collections/show.html.erb, app/views/content_providers/show.html.erb, app/views/learning_path_topics/show.html.erb, app/views/nodes/show.html.erb, app/views/users/show.html.erb, test/controllers/content_providers_controller_test.rb, test/controllers/users_controller_test.rb
- Show upcoming count instead of all event count (with asterisk if no upcoming but some past events).
Past events are not as relevant to users.
**Checklist**
=> Only count upcoming events in tab title

app/views/about/_about_nav.html.erb, app/views/about/tess.html.erb, config/locales/en.yml
Making sure the entire view for the about page goes through i18n.
There are a lot of strings on the about page that don't go through i18n. This fixes that.
**Checklist**
=> Making entire about page content go through i18n.

app/assets/javascripts/application.js, app/assets/javascripts/learning_paths.js, app/controllers/materials_controller.rb, app/helpers/learning_paths_helper.rb, app/models/learning_path_topic_item.rb, app/models/learning_path_topic_link.rb, app/views/events/_event.html.erb, app/views/learning_path_topic_items/_learning_path_topic_item.html.erb, app/views/learning_paths/partials/_navigation.html.erb, app/views/learning_paths/show.html.erb, app/views/materials/_material.html.erb, app/views/materials/show.html.erb, config/locales/en.yml, test/controllers/learning_paths_controller_test.rb, test/controllers/materials_controller_test.rb, test/models/learning_path_test.rb, test/models/learning_path_topic_test.rb
- When clicking through to a material from a learning path, adds a parameter to the URL with a reference back to the learning path/topic.
- If this parameter is present, displays a box in the left sidebar showing: the current learning path and topic, the comment on this item (if present), and a link to either the next item in the topic, or the next topic in the learning path (if there is one).
#997
**Checklist**
=> Show learning path navigation box when looking at an item from a learning path

app/controllers/communities_controller.rb, app/models/event.rb, test/models/event_test.rb
- Tweaks the logic for selecting events to display (& adds test)
It was showing an event from 2015:
**Checklist**
=> Fix upcoming event listing on community page

app/views/layouts/_footer.html.erb, app/views/layouts/_supported_by.erb, config/locales/en.yml
Ensure that the page footers fully go through i18n.
Included: make the EU Funding statement go through the t() view helper (and flagged as having html content, which ensures they are escaped properly).
Trying to make TeSS more fully i18n capable.
**Checklist**
=> i18n for page footer.

app/views/content_providers/show.html.erb
Sort events on provider show page by start date
**Checklist**
=> sorted provider events

app/views/layouts/_user_menu.html.erb, config/locales/en.yml
The strings in the user menu weren't going through i18n ... now they do.
String that don't go through i18n aren't translatable.
Looks exactly the same as before.
**Checklist**
=> Make the strings in the user menu go through i18n.

public/api/definitions/tess.yml
- Update the API schema with some missing/wrong filter options.
I needed to use the event `start` filter in the TeSS Widget, which uses a JSON API client generated from the spec.
**Checklist**
=> Add missing filters to API spec

lib/scraper.rb, test/config/test_ingestion_bad.yml, test/controllers/application_controller_test.rb, test/models/profile_test.rb, test/models/source_test.rb, test/test_helper.rb, test/unit/image_attachment_test.rb, test/unit/ingestors/scraper_test.rb
- Removes the `validate_url` call when running a source through a `Scraper`.
- Ensures no external network requests are made when running tests.
- Adds a `with_net_connection` test method to allow real network calls in tests if needed (currently used to test `private_address_check` is working).
A user created a source with a URL that returned a 301 redirect. This worked fine when testing, but was considered invalid when running through the scraper. The URL format is already validated when creating a source, and any issues when resolving the URL should be raised when running the actual `Ingestor`.
**Checklist**
=> Remove source URL validation in scraper

app/policies/collection_policy.rb, test/controllers/collections_controller_test.rb
- Fixes collection policy which was only allowing "managers" to see the collection.
User who was a collaborator on a private collection could not view it, although could load the edit page and make changes.
**Checklist**
=> Ensure collaborators can see private collections

app/views/search/common/_facet_sidebar.html.erb, app/views/search/common/_facet_sidebar_curation.html.erb, app/views/search/common/_facet_sidebar_max_age.html.erb, app/views/search/common/_search_filters.html.erb, config/locales/en.yml
i18n for many parts of search.
Many strings in the view don't go through i18n, this fixes some of them.
**Checklist**
- [ x] I have read and followed the [CONTRIBUTING](https://github.com/ElixirTeSS/TeSS/blob/master/CONTRIBUTING.md) guide.
- [x ] I confirm that I have the authority necessary to make this contribution on behalf of its copyright owner and agree
=> i18n for many parts of search.

app/helpers/materials_helper.rb, app/models/event.rb, app/views/events/_form.html.erb, test/controllers/events_controller_test.rb
Hide disabled fields on show page in addition to form page, also add some fields to be disabled for events
**Checklist**
=> hide disabled fields in show page

CONTRIBUTORS.md, config/application.rb, config/environments/production.rb, config/environments/test.rb, config/tess.example.yml, docker/tess.docker-test.yml, lib/tess/i18n.rb, test/config/test_tess.yml
The main changes allow for configuring I18n from tess.yml.
This allows each deployment of TeSS to configure I18n without having to maintain local code customizations. This in turn is motivated by requirements of the National Training Discovery portal project of the Digital Research Alliance of Canada.
No visible changes.
**Checklist**
=> Configure I18n from tess.yml

app/assets/javascripts/autocompleters.js, app/assets/javascripts/collections.js, app/assets/javascripts/learning_paths.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/collection.scss, app/views/collections/_collection_items_form.erb, app/views/collections/_form.html.erb, app/views/learning_paths/_form.html.erb, app/views/workflows/_form.html.erb, config/locales/en.yml
- Adds a dropdown list of user's own topics in addition to search field.
- Moves some hard-coded text into translation files.
Generally users want to add their own topics to a learning path.
**Checklist**
=> Easier selection of user's own topics when making learning paths

docs/docker.md, docs/install.md, lib/tasks/tess.rake
- Adds `tess:reindex` which indexes upcoming events and materials before other resources.
When running `sunspot:reindex` it will drop the index of each model and then reindex every resource, which can lead to long periods of time where the index pages are blank while it indexes e.g. thousands of expired events.
**Checklist**
=> Add a rake task that prioritizes solr reindexing to minimize downtime

app/controllers/sources_controller.rb, app/models/source.rb, app/views/sources/_form.html.erb, app/views/sources/show.html.erb, config/locales/en.yml, db/migrate/20250303210238_add_default_language_to_source.rb, db/schema.rb, lib/ingestors/ingestor.rb, lib/scraper.rb, test/unit/ingestors/ingestor_test.rb
Hi Finn, this is a feature we are going to implement on our side, so I thought I would check if there was an appetite for it upstream. Feel free to reject it if you think it's a bad fit, or suggest some improvements if it's "almost there".
This adds an additional column called `default_language` to the `Source` model. The idea is that when an ingestor/scraper ingests events from this source, it will set the language of an event to the source default language (provided that a language isn't set for the event already)
In our case, we have regions that are more likely to use one language than another. So it is useful for us to set this as an option for a `Source` to inject a `language` into events that are read as a default. This could have …
=> Source default language

app/controllers/subscriptions_controller.rb, app/helpers/subscriptions_helper.rb, app/views/subscriptions/_subscribe_button.html.erb, app/views/subscriptions/_subscribe_to_calendar_modal.html.erb, app/views/subscriptions/_subscribe_to_rss_modal.html.erb, app/views/subscriptions/_subscription.html.erb, app/views/subscriptions/index.html.erb, app/views/subscriptions/unsubscribe.html.erb, config/locales/en.yml
Removing strings from view/controllers/helpers related to subscriptions and using i18n instead.
Well, everything should go through i18n...
Looks the same.
**Checklist**
=> Make view content related to subscriptions go through i18n.

app/dictionaries/language_dictionary.rb, app/views/sources/show.html.erb
A unwanted value was returned when a source's default language is blank.
This fix repairs that.
Fix for #1099 
**Checklist**
=> Handle an unset value for default_language for a source.

app/views/public_activity/common/_create.html.erb, lib/ingestors/ingestor.rb, test/controllers/activities_controller_test.rb, test/unit/ingestors/scraper_test.rb
- Ensures a `PublicActivity::Activity` is created when a resource is created/update via the scraper, to match the behaviour of the UI
- Displays some info on the `Source` where the resource was scraped from under the activity in the log (only visible to administrators and curators)
The "Activity Log" for scraped resources was confusing as it only listed parameter changes. Additionally, if multiple sources updated the same resource, it was difficult to track down which.
**Checklist**
=> Log activity when resources are scraped

app/assets/javascripts/application.js, app/helpers/materials_helper.rb, app/views/common/_extra_metadata.html.erb, app/views/layouts/_user_menu.html.erb, app/views/learning_paths/show.html.erb
- Add `expandable` option to `display_attribute`, which limits the max vertical height of the attribute value, adding a "See more/less" link to expand/collapse.
- Makes expandable elements expand to max height when "See more" is clicked, instead of gradually showing more content.
- Add some spacing between icons and text in user menu.
#1096
**Checklist**
=> Collapse long learning objective/pre-requisite fields when viewing a learning path

app/views/events/_form.html.erb, app/views/materials/_form.html.erb, config/locales/en.yml
- Allow event/material visibility checkbox to be disabled
- Display the hint at all times, without requiring hover
- I18n
A user wasn't clear about what the checkbox does, and it is the first thing you see on the new event form
**Checklist**
=> Visibility feature tweaks

app/controllers/users_controller.rb, app/helpers/search_helper.rb, app/models/concerns/searchable.rb, app/models/profile.rb, app/models/trainer.rb, app/views/users/_form.html.erb, config/locales/en.yml, test/controllers/trainers_controller_test.rb, test/controllers/users_controller_test.rb, test/fixtures/profiles.yml, test/fixtures/users.yml, test/test_helper.rb
- Prevents a new profile record being created each time the user updates their profile.
- Fixes trainer language filter options being blank
- Fixes trainer filters showing even when no trainers in the list
- Fixes 500 when trying to edit profile as an admin
- Refactors trainer/profile reindexing behaviour (no longer requires full reindex when a single record changes)
User noticed trainer language select on profile edit page was showing Yes/No options instead of languages, ran into other issues whilst debugging.
**Checklist**
=> Profile form fixes

app/views/static/home/_search_box.html.erb, app/views/static/home/_welcome.html.erb, config/tess.example.yml, test/controllers/static_controller_test.rb
Fixes #1122 
- made the search box modular, see `app/views/static/home/_search_box.html.erb`
- in `tess.example.yml` there is now a `home_page.search_box` option.
- I added the relevant tests also to see whether 'searchbox' is present in html
See #1122
**Checklist**
=> Option: search_box

app/models/profile.rb
- `profile.rb`: calling reindex_trainer only when creating and updating, not deleting.
When deleting a user, a FrozenError was raised, this is due to the `reindex_trainer` method of the `Profile` model being called after a commit.
**Discussions**
One question raised by Finn was *"we need to check what happens to the search index when the profile is deleted (e.g. does it cause an error because the profile is returned from the search service but can't be found in the database anymore)"*
1. Register user, delete immediately:
a. They are present in table users, not in table profiles, not in solr
b. Deleting does the FrozenError
c. Then they are not present in db anymore (nor in solr)
2. Register user, update profile, not ticking trainer
a. …
=> FrozenError on profile/user delete

app/views/about/tess.html.erb, config/locales/en.yml
- Add a paragraph about mTeSS-X to the About page.
- Link to the mTeSS-X project website.
- Action from weekly TeSS project meeting on 2025-08-11
**Checklist**
=> Add mTeSS-X paragraph to About page

app/models/link_monitor.rb, test/models/link_monitor_test.rb
- Trigger a reindex of an event/material if its URL is detected as being broken (or back online)
Resources with dead links were showing up in search results due to not being indexed after the link monitor updated.
**Checklist**
=> Reindex resource when link status changes

lib/ingestors/material_csv_ingestor.rb, test/unit/ingestors/material_csv_ingestor_test.rb
- `lib/ingestors/material_csv_ingestor.rb`: modify the given url to a Google sheet csv export URL if it has`docs.google.com/spreadsheets` – the rest is taken care of the csv ingestor as usual.
After a discussion with Phil and Finn when I presented the following workflow (see https://github.com/EVERSE-ResearchSoftware/training):
1. Through a GH action, exporting google sheet csv
2. Translating to a JSON-LD format
3. Push the changes on the GH repo to have TeSS fetching the metadata on the raw JSON-LD file
Finn asked whether it would be possible to do it in TeSS directly. Here it is.
**Checklist**
=> Google sheet material ingestion
