config/initializers/devise.rb

To fix `JSON::JWS::VerificationFailed`
Keys from: https://login.elixir-czech.org/oidc/jwk

Update `client_jwk_signing_key` in AAI config

---

README.md
config/routes.rb
docker-compose-prod.yml

I've updated the README to ensure people don't accidentally reuse the provided `SECRET_BASE_KEY` for their production sites.
Besides that there is a small change to config/routes.rb to fix a problem encountered when doing a `db:setup`, and a traefik configuration change that seemed necessary for us to get our staging server up and running.

Update deployment instructions

---

db/seeds.rb

The check in user.rb is for "1" explicitly, so let's also do it that way in the seeds.rb.

Fix issue with seeding database

---

app/assets/stylesheets/application.scss
app/helpers/materials_helper.rb
app/views/materials/show.html.erb
lib/renderers/youtube.rb
test/controllers/materials_controller_test.rb
test/fixtures/external_resources.yml
test/fixtures/materials.yml
test/unit/renderer_test.rb

Embed Youtube video for materials that link to Youtube

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/epic-enhancements.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/pull_request_template.md
CONTRIBUTING.md
CONTRIBUTORS.md
README.md
docs/api.md

Updates `CONTRIBUTING.md` and some issue/PR templates.

Community standards improvements

---

app/assets/javascripts/biotools.js
app/assets/javascripts/templates/events/event_on_map.hbs
app/helpers/application_helper.rb
app/views/about/developers.erb
app/views/about/us.html.erb
app/views/common/_external_resource.html.erb
app/views/content_providers/partials/_content_provider_info.html.erb
app/views/content_providers/show.html.erb
app/views/curator/users.html.erb
app/views/devise/registrations/new.html.erb
app/views/events/show.html.erb
app/views/layouts/_supported_by.erb
app/views/materials/show.html.erb
app/views/nodes/partials/_node_info.html.erb
app/views/nodes/show.html.erb
app/views/sources/_test_results.html.erb
app/views/sources/show.html.erb
app/views/subscriptions/_subscribe_to_calendar_modal.html.erb
app/views/trainers/show.html.erb
config/locales/en.yml

Add `rel="noopener"` for external links. Fixes #770

---

app/models/concerns/with_timezone.rb
app/models/event.rb

- Extract timezone validation from event into a concern
Simplify the `Event` model and be ready for reuse in other contexts (Subscription emails?)
**Checklist**

extract timezone handling from event into concern

---

db/migrate/20170307113734_remove_old_index_and_foreign_key_from_edit_suggestions.rb
db/migrate/20180426141503_fix_nil_sponsors.rb
db/migrate/20230103132957_upgrade_paperclip_attachment_size_to_big_int.rb
db/migrate/20230204095643_remove_keyword_from_materials.rb
db/schema.rb

- Fixes some broken migrations
- Removes a rogue column that was introduced to the schema without a migration
- Updates some paperclip columns
There was not a clean migration path due to (presumably) `ActiveRecord::Migration` changes.
**Checklist**

Schema fixes

---

CONTRIBUTING.md
config/initializers/sprockets.rb
docker-compose.yml
docs/docker.md

- Adds a method for running tests to the dev docker-compose file
- Stop dev containers starting on boot
- Mention docker in CONTRIBUTING guide
Response to comments about reducing the effort involve in contributing a fix to TeSS
**Checklist**

Docker improvements + docs

---

app/helpers/application_helper.rb
app/views/events/show.html.erb
app/views/materials/show.html.erb
config/locales/en.yml
test/controllers/events_controller_test.rb
test/controllers/materials_controller_test.rb

- As in title
#823
**Checklist**

Show warning on show page for resources where link is broken. Fixes #823

---

app/views/about/registering.html.erb
app/views/about/tess.html.erb
config/locales/en.yml

Added hardcoded text to locale translations
Want to override these translations in taxila
**Checklist**

added lines to translations in about page

---

app/views/about/tess.html.erb
config/locales/en.yml

Added translations to for subscriptions manager
Override these translations in taxila
**Checklist**

added translation for subscription manager

---

app/controllers/events_controller.rb
app/controllers/materials_controller.rb
app/models/event.rb
app/models/material.rb
app/policies/material_policy.rb
app/views/materials/show.html.erb
config/routes.rb
test/controllers/events_controller_test.rb
test/controllers/materials_controller_test.rb
test/models/event_test.rb
test/models/material_test.rb

- Adds "Clone" button to materials.
- Copy various associations when cloning (linked materials/events/nodes, external resources, scientific topics etc.).
#762 
#795 
**Checklist**

Cloning improvements

---

app/views/collections/index.html.erb
app/views/content_providers/index.html.erb
app/views/elearning_materials/index.html.erb
app/views/events/index.html.erb
app/views/layouts/_header.html.erb
app/views/materials/index.html.erb
app/views/nodes/index.html.erb
app/views/static/home/_catalogue_blocks.html.erb
app/views/trainers/index.html.erb
app/views/workflows/index.html.erb
config/locales/en.yml

I18n translations for features so that they can be overwritten in Taxila
(Tag any relevant issues or discussions with #, or write a brief explanation of why you are making this PR)
**Checklist**

translations for the features

---

app/assets/javascripts/application.js
app/assets/javascripts/autocompleters.js
app/assets/javascripts/collections.js
app/assets/javascripts/templates/autocompleter/collection_item.hbs
app/assets/stylesheets/collection.scss
app/assets/stylesheets/masonry.scss
app/controllers/collections_controller.rb
app/helpers/collections_helper.rb
app/models/collection.rb
app/views/collection_items/_collection_item.html.erb
app/views/collections/_collection_items_form.erb
app/views/collections/_form.html.erb
app/views/collections/show.html.erb
app/views/events/_event.html.erb
app/views/materials/_material.html.erb
test/controllers/collections_controller_test.rb
test/models/collection_test.rb
vendor/assets/javascripts/sortable.js

- Allow collection items to be ordered via the edit form.
- Allow collection items to have a comment added via the edit form.
- Display collection items according to the defined order, along with the comment if present.
Fixes #724
**Checklist**

Collection improvements

---

app/views/about/_about_nav.html.erb
app/views/about/us.html.erb
config/locales/en.yml
config/tess.example.yml

Option to change order or leave out options for 'about us' page. Request from taxila
(Tag any relevant issues or discussions with #, or write a brief explanation of why you are making this PR)
**Checklist**

added option to change order or leave out options for about us

---

Gemfile
Gemfile.lock
app/controllers/bioschemas_controller.rb
app/controllers/events_controller.rb
app/controllers/materials_controller.rb
app/models/concerns/has_test_job.rb
app/views/bioschemas/_preview_button.html.erb
app/views/bioschemas/_test_results.html.erb
app/views/bioschemas/test.html.erb
app/views/events/show.html.erb
app/views/layouts/_footer.html.erb
app/views/materials/show.html.erb
app/views/sources/_test_resource.html.erb
app/views/sources/_test_results.html.erb
config/routes.rb
config/tess.example.yml
lib/ingestors/bioschemas_ingestor.rb
lib/ingestors/event_ingestion.rb
lib/ingestors/material_ingestion.rb
test/config/test_tess.yml
test/controllers/bioschemas_controller_test.rb
test/controllers/events_controller_test.rb
test/controllers/materials_controller_test.rb
test/fixtures/files/ingestion/ext_res.json
test/fixtures/files/ingestion/gtn/slides-introduction-modified.html
test/unit/ingestors/bioschemas_ingestor_test.rb

- Adds a page where a single Bioschemas-containing URL or code snippet can be tested.
- Adds the ability to "preview" how a Bioschemas resource will appear as a TeSS event/material.
Allows users to debug their Bioschemas implementation, and ensure their events/materials will appear exactly as intended.
**Checklist**

Bioschemas testing tool

---

lib/ingestors/tdcc_ingestor.rb

Assume that any event with an end date more than a week past is for next year
Future events for taxila registered as past events since no year was explicitly given
**Checklist**

tdcc ingestor year

---

lib/ingestors/surf_ingestor.rb
test/unit/ingestors/surf_ingestor_test.rb

Surf ingestor was no longer working
**Checklist**

fix surf ingestor

---

lib/bioschemas/course_instance_generator.rb
lib/bioschemas/event_generator.rb
lib/bioschemas/generator.rb
test/integration/bioschemas_test.rb

- Changes `location` from `PostalAddress` to `Place`, with lat/lon on the `Place` and the `PostalAddress` fields under `address`
#902
**Checklist**

Fix `location` value in Bioschemas markup

---

lib/ingestors/osci_ingestor.rb

Failing osci scraper since key could not be found
**Checklist**

fix osci event key

---

app/models/source.rb
app/views/bioschemas/_preview_button.html.erb
app/views/sources/index.html.erb

- Allow filtering of sources by ELIXIR node
- Add missing pagination bar to source index
- Fix being unable to preview a resource more than once via Bioschemas testing page
Need to check which nodes/providers have implemented Bioschemas for reporting purposes.
**Checklist**

Source improvements & fixes

---

app/dictionaries/licence_dictionary.rb
app/models/concerns/has_licence.rb
lib/ingestors/zenodo_ingestor.rb
test/config/test_ingestion_rest.yml
test/fixtures/files/ingestion/zenodo_abt.json
test/fixtures/files/ingestion/zenodo_ardc.json
test/fixtures/files/ingestion/zenodo_ardc_2.json
test/fixtures/files/ingestion/zenodo_ardc_3.json
test/models/material_test.rb
test/test_helper.rb
test/unit/ingestors/zenodo_ingestor_test.rb

- Some updates to the Zenodo ingestor to cope with changes to their API
- Use case-insensitive matching of incoming license IDs
- Update fixtures containing Zenodo responses
DReSA team reported Zenodo ingestor was failing to scrape resources.
**Checklist**

Zenodo ingestor fix

---

lib/ingestors/tdcc_ingestor.rb

Fix new case of inconsistent tdcc ingestor end date
**Checklist**

fix case for 2 length end date

---

app/helpers/application_helper.rb
app/views/trainers/index.html.erb
app/views/users/_form.html.erb

Only show 'register as trainer' button if trainers turned on, set anchor for link, move 'show trainer details' checkbox up in trainer form
Clarity for users
**Checklist**

register as trainer clarity

---

app/controllers/static_controller.rb

Only return 1 event per provider in upcoming events
Prevents it from being dominated by single provider with 4 events on same day
**Checklist**

Provider separated upcoming events

---

app/controllers/static_controller.rb
app/views/static/home.html.erb
app/views/static/home/_featured_trainer.html.erb
config/tess.example.yml
test/controllers/static_controller_test.rb

Option to show daily featured trainer on home page
Taxila
**Checklist**

Optional daily featured trainer on home page

---

app/views/events/_event.html.erb
config/tess.example.yml
test/controllers/events_controller_test.rb

Enable showing provider logo in events
**Checklist**

optional provider logo in events

---

app/views/content_providers/_content_provider.html.erb
config/tess.example.yml
test/controllers/content_providers_controller_test.rb

Optional grid masonry for index page of content providers
**Checklist**

optional grid masonry for content provider index

---

app/assets/stylesheets/home.scss
app/views/static/home/_featured_trainer.html.erb
app/views/static/home/_latest_materials.erb
app/views/static/home/_provider_carousel.html.erb
app/views/static/home/_upcoming_events.html.erb

home page titles with links to index pages

---

app/assets/stylesheets/home.scss
app/controllers/static_controller.rb
app/views/static/home.html.erb
app/views/static/home/_catalogue_blocks.html.erb
app/views/static/home/_counters.html.erb
config/tess.example.yml
test/controllers/static_controller_test.rb

smaller blocks specifically for counters
Taxila
**Checklist**

counter blocks with logos

---

app/views/common/_multiple_input.html.erb

Add id in multi_input form fields
Ability to selectively disable fields in taxila
**Checklist**

id in multi_input form

---

app/views/collections/index.html.erb
app/views/content_providers/index.html.erb
app/views/events/index.html.erb
app/views/materials/index.html.erb
app/views/trainers/index.html.erb
app/views/workflows/index.html.erb
config/locales/en.yml

translations for registration buttons

---

app/controllers/static_controller.rb

No time cap on latest materials

---

app/controllers/application_controller.rb
app/validators/http_url_validator.rb
app/workers/edit_suggestion_worker.rb
lib/tasks/check_urls.rake

- Catch some extra exceptions
Sentry was reporting occasional 500 errors from production.
**Checklist**

Exception handling

---

lib/tasks/tess.rake

deliver_later for curation mail func

---

app/views/curation_mailer/events_require_approval.html.erb
app/views/curation_mailer/events_require_approval.text.erb

Add some instruction on how to best change scraped events.
Clarity for curators to prevent changed events being rewritten againon scrape
**Checklist**

add explanation text to mail

---

app/assets/stylesheets/home.scss

Make it so that these blocks have the same background color as the other home page objects
taxila with different background color looked weird for these blocks 
**Checklist**

home page block color

---

app/mailers/curation_mailer.rb
config/locales/en.yml
test/mailers/curation_mailer_test.rb

Set curation mailer subject from locale

---

app/controllers/content_providers_controller.rb
app/mailers/curation_mailer.rb
app/views/content_providers/_form.html.erb
db/migrate/20240530064523_change_event_curatition_email_to_string.rb
db/schema.rb
lib/tasks/tess.rake
test/fixtures/content_providers.yml
test/mailers/curation_mailer_test.rb

send mail to profile email instead of user email

---

config/application.rb
config/locales/en.yml
lib/scraper.rb
test/unit/ingestors/scraper_test.rb

- Extracts individual source scraping into a method
I had a need to run a one-off scrape of a single source via the console
**Checklist**

Minor scraper refactor

---

app/controllers/application_controller.rb
app/models/collection.rb
app/models/learning_path_topic.rb
config/locales/en.yml
config/routes.rb
lib/tasks/check_urls.rake
test/integration/error_handler_test.rb

- Improve error page rendering to cope with unknown format.
- Remove stub methods that were causing a non-functioning filter to be rendered.
- Reduce sleep time in URL checker task.
Various prod errors were logged via Sentry, and noticed long-running ruby process for URL checker task.
**Checklist**

Misc fixes

---

app/dictionaries/language_dictionary.rb

safe navigation capitalize

---

config/schedule.rb
lib/tasks/tess.rake

skip post processing in task instead of scheduler

---

config/locales/en.yml

- Add one sentence to internal editorial processes for learning paths doc.
- Aligned to ELIXIR TeSS Club action.
**Checklist**
- [ x] I have read and followed the [CONTRIBUTING](https://github.com/ElixirTeSS/TeSS/blob/master/CONTRIBUTING.md) guide.
- [x ] I confirm that I have the authority necessary to make this contribution on behalf of its copyright owner and agree

Add sentence on internal editorial process to LP docs

---

app/assets/stylesheets/home.scss

Fix box size for provider grid
Sometimes got weird small tiles for certain images
Before:
After:
**Checklist**

Fixed height and width for provider grid images

---

app/views/elearning_materials/index.html.erb
app/views/events/index.html.erb
app/views/learning_paths/index.html.erb
app/views/materials/index.html.erb
app/views/search/common/_search_panel.html.erb
app/views/subscriptions/_subscribe_button.html.erb

moved subscription button up and increased size for better visibility

---

test/test_helper.rb

fix webmock stub for willma login

---

app/views/subscriptions/_subscribe_button.html.erb

Subscribe button dropdown appears again
**Checklist**

repair subscribe button

---

app/views/devise/sessions/_omniauth_options.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/locales/devise.en.yml
config/locales/en.yml

I18n for some of the devise related pages.
Fixing some strings that don't currently go though i18n.
**Checklist**

I18n for some of the devise related pages.

---

CONTRIBUTORS.md

add mike sanders to contributors

---

lib/ingestors/lcrdm_ingestor.rb

LCRDM scraper choose next year if event in past
**Checklist**

lcrdm choose next year if event longer than 2 weeks ago

---

app/models/material.rb
app/views/content_providers/_content_provider.html.erb
app/views/content_providers/show.html.erb
lib/facets.rb
test/controllers/content_providers_controller_test.rb

Disabled materials would still show up in list
**Checklist**

do not show disabled materials on material index and provider show

---

config/application.rb
config/environments/production.rb

Re-applying changes from the configurable I18n changes that were accidentally reverted with the Rails 7.1/7.2 upgrades.
**Checklist**

Fix configurable i18n

---

docker-compose-prod.yml

restart sidekiq container
mailers stopped working on taxila
**Checklist**

restart sidekiq

---

.github/workflows/docker-test.yml
Gemfile
Gemfile.lock
app/policies/learning_path_topic_policy.rb
docker-compose-prod.yml
docker-compose.yml
test/controllers/learning_path_topics_controller_test.rb

- Allows users with the "learning path curator" role to correctly manage learning path topics.
- Bumps sunspot gem version to fix logging error
- Works around docker compose bug causing failure in Action
User reported being unable to create topic when building a learning path.
**Checklist**

Learning path curator role fix

---

lib/ingestors/taxila/uu_ingestor.rb

Set visible to default false for UU scraper.
Majority filtered out in practice
**Checklist**

uu ingestors opt in strategy
